// <auto-generated />
using System;
using CadContato.Domain.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadContato.Domain.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210121123915_First Version")]
    partial class FirstVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CadContato.Domain.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("CadContato.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CadContato.Domain.Entities.Contato", b =>
                {
                    b.HasOne("CadContato.Domain.Entities.User", "User")
                        .WithMany("Contatos")
                        .HasForeignKey("UserId");

                    b.OwnsOne("CadContato.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ContatoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("")
                                .HasColumnName("Email");

                            b1.HasKey("ContatoId");

                            b1.ToTable("Contato");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.OwnsOne("CadContato.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("ContatoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PrimeiroNome")
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("UltimoNome")
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("")
                                .HasColumnName("UltimoNome");

                            b1.HasKey("ContatoId");

                            b1.ToTable("Contato");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.OwnsOne("CadContato.Domain.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("ContatoId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("DDD")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TelefoneDDD");

                            b1.Property<int?>("Numero")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TelefoneNumero");

                            b1.HasKey("ContatoId");

                            b1.ToTable("Contato");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Nome");

                    b.Navigation("Telefone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CadContato.Domain.Entities.User", b =>
                {
                    b.OwnsOne("CadContato.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("EmailUser");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("CadContato.Domain.Entities.User", b =>
                {
                    b.Navigation("Contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
